buildscript
{
    repositories
    {
        jcenter()
		maven { url = "https://files.minecraftforge.net/maven" }
	}
	dependencies {classpath 'net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT'}
}
apply plugin: 'net.minecraftforge.gradle.forge'
project.mkdir "libs"
sourceCompatibility = targetCompatibility = compileJava.sourceCompatibility = compileJava.targetCompatibility = '1.8'

version = "0.8.6-indev"
group = "net.minecraft.AgeOfMinecraft"
archivesBaseName = "Engender_Mod"

minecraft
{
    version = "1.12.2-14.23.5.2847"
    runDir = "run"
    mappings = "snapshot_20171003"
    makeObfSourceJar = false
}

repositories
{
	maven
	{
		name 'Progwml6'
		url "http://dvs1.progwml6.com/files/maven"
	}
}

dependencies
{
   runtime "mezz.jei:jei_1.12.2:4.13.1.225"
}

processResources
{
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version
    from(sourceSets.main.resources.srcDirs)
    {
        include 'mcmod.info'
        expand 'version':project.version, 'mcversion':project.minecraft.version
    }
    from(sourceSets.main.resources.srcDirs) {exclude 'mcmod.info'}
   //rename '(ender_at.cfg)', 'META-INF/$1'
}
//jar {manifest {attributes 'FMLAT': 'ender_at.cfg'}}