org.gradle.jvmargs=-Xmx3G

#Environmental Settings
minecraft_version=1.12.2
minecraft_mappings=snapshot_20171003
forge_version=14.23.5.2847
jei_version=4.13.1.225
codechicken_version=3.2.3.358
bookshelf_version=2.3.590
baubles_version=1.5.2


#Mod Settings
mod_group=net.mrbt0907.ageofminecraft
mod_name=Engender Mod
mod_version=1.0
at_mixin_name=engender