package net.minecraft.AgeOfMinecraft.registry;

import java.util.ArrayList;
import java.util.List;

import net.minecraft.AgeOfMinecraft.items.*;
import net.minecraft.block.BlockDispenser;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.ItemModelMesher;
import net.minecraft.client.renderer.block.model.ModelResourceLocation;
import net.minecraft.dispenser.BehaviorDefaultDispenseItem;
import net.minecraft.dispenser.IBlockSource;
import net.minecraft.entity.Entity;
import net.minecraft.item.Item;
import net.minecraft.item.Item.ToolMaterial;
import net.minecraft.item.ItemSimpleFoiled;
import net.minecraft.item.ItemStack;
import net.minecraft.util.EnumFacing;
import net.minecraftforge.registries.GameData;


public class EItem
{
	public static ItemManaCollector manaContainer;
	public static ItemManaCollector entropyContainer;
	public static ItemManaCollector artifact1;
	public static Item witheredNetherStar;
	public static Item woodencleaver;
	public static Item stonecleaver;
	public static Item ironcleaver;
	public static Item goldencleaver;
	public static Item diamondcleaver;
	public static Item statChecker;
	public static Item carrier;
	public static Item heromaker;
	public static Item lastchance;
	public static Item trainingstick;
	public static Item blowhorn;
	public static Item blowhorn2;
	public static Item convertingStaff;
	public static Item summoningStaff;
	public static Item commandingStaff;
	public static Item portalStaff;
	public static ItemLearningBook learningBookBasic;
	public static ItemLearningBook learningBookBasicCombat;
	public static ItemLearningBook learningBookBasicCooking;
	public static ItemLearningBook learningBookBasicExercise;
	public static ItemLearningBook learningBookBasicKnowledge;
	public static ItemLearningBook learningBookModern;
	public static ItemLearningBook learningBookModernCombat;
	public static ItemLearningBook learningBookModernBrute;
	public static ItemLearningBook learningBookModernCooking;
	public static ItemLearningBook learningBookModernEating;
	public static ItemLearningBook learningBookModernExercise;
	public static ItemLearningBook learningBookModernRunning;
	public static ItemLearningBook learningBookModernKnowledge;
	public static ItemLearningBook learningBookModernPacifist;
	public static ItemLearningBook learningBookAdvanced;
	public static ItemLearningBook learningBookAdvancedCombat;
	public static ItemLearningBook learningBookAdvancedBrute;
	public static ItemLearningBook learningBookAdvancedWarrior;
	public static ItemLearningBook learningBookAdvancedCooking;
	public static ItemLearningBook learningBookAdvancedEating;
	public static ItemLearningBook learningBookAdvancedDieting;
	public static ItemLearningBook learningBookAdvancedExercise;
	public static ItemLearningBook learningBookAdvancedRunning;
	public static ItemLearningBook learningBookAdvancedLifting;
	public static ItemLearningBook learningBookAdvancedKnowledge;
	public static ItemLearningBook learningBookAdvancedPacifist;
	public static ItemLearningBook learningBookAdvancedWisdom;
	
	public static ItemLearningBook learningBookComplex;
	public static ItemLearningBook learningBookComplexCombat;
	public static ItemLearningBook learningBookComplexBrute;
	public static ItemLearningBook learningBookComplexWarrior;
	public static ItemLearningBook learningBookComplexCooking;
	public static ItemLearningBook learningBookComplexEating;
	public static ItemLearningBook learningBookComplexDieting;
	public static ItemLearningBook learningBookComplexExercise;
	public static ItemLearningBook learningBookComplexRunning;
	public static ItemLearningBook learningBookComplexLifting;
	public static ItemLearningBook learningBookComplexKnowledge;
	public static ItemLearningBook learningBookComplexPacifist;
	public static ItemLearningBook learningBookComplexWisdom;
	public static ItemLearningBook learningBookMaster;
	public static ItemLearningBook learningBookMasterCombat;
	public static ItemLearningBook learningBookMasterBrute;
	public static ItemLearningBook learningBookMasterWarrior;
	public static ItemLearningBook learningBookMasterCooking;
	public static ItemLearningBook learningBookMasterEating;
	public static ItemLearningBook learningBookMasterDieting;
	public static ItemLearningBook learningBookMasterExercise;
	public static ItemLearningBook learningBookMasterRunning;
	public static ItemLearningBook learningBookMasterLifting;
	public static ItemLearningBook learningBookMasterKnowledge;
	public static ItemLearningBook learningBookMasterPacifist;
	public static ItemLearningBook learningBookMasterWisdom;
	public static ItemLearningBook learningBookArtifactStrength;
	public static ItemLearningBook learningBookArtifactStamina;
	public static ItemLearningBook learningBookArtifactSpeed;
	public static ItemLearningBook learningBookArtifactIntellegence;
	public static ItemLearningBook learningBookArtifact;
	public static ItemFusion fusionItemBat;
	public static ItemFusion fusionItemChicken;
	public static ItemFusion fusionItemCow;
	public static ItemFusion fusionItemMooshroom;
	public static ItemFusion fusionItemParrot;
	public static ItemFusion fusionItemPig;
	public static ItemFusion fusionItemRabbit;
	public static ItemFusion fusionItemSheep;
	public static ItemFusion fusionItemOzelot;
	public static ItemFusion fusionItemSquid;
	public static ItemFusion fusionItemVillager;
	public static ItemFusion fusionItemSnowman;
	public static ItemFusion fusionItemSilverfish;
	public static ItemFusion fusionItemEndermite;
	public static ItemFusion fusionItemWolf;
	public static ItemFusion fusionItemSpider;
	public static ItemFusion fusionItemZombie;
	public static ItemFusion fusionItemSkeleton;
	public static ItemFusion fusionItemCreeper;
	public static ItemFusion fusionItemSlime;
	public static ItemFusion fusionItemMagmaCube;
	public static ItemFusion fusionItemSpiderJockey;
	public static ItemFusion fusionItemChickenJockey;
	public static ItemFusion fusionItemBlaze;
	public static ItemFusion fusionItemEnderman;
	public static ItemFusion fusionItemCaveSpider;
	public static ItemFusion fusionItemPigZombie;
	public static ItemFusion fusionItemGuardian;
	public static ItemFusion fusionItemGhast;
	public static ItemFusion fusionItemWitch;
	public static ItemFusion fusionItemWitherSkeleton;
	public static ItemFusion fusionItemKillerRabbit;
	public static ItemFusion fusionItemElderGuardian;
	public static ItemFusion fusionItemGiant;
	public static ItemFusion fusionItemVillagerGolem;
	public static ItemFusion fusionItemEnderDragon;
	public static ItemFusion fusionItemWither;
	public static ItemFusion fusionItemShulker;
	public static ItemFusion fusionItemSkeletonTrap;
	public static ItemFusion fusionItemStray;
	public static ItemFusion fusionItemHusk;
	public static ItemFusion fusionItemPolarBear;
	public static ItemFusion fusionItemVex;
	public static ItemFusion fusionItemVindicator;
	public static ItemFusion fusionItemLlama;
	public static ItemFusion fusionItemEvoker;
	public static ItemFusion fusionItemEversource;
	public static ItemFusion fusionItemIceSpider;
	public static ItemFusion fusionItemCreeder;
	public static ItemFusion fusionItemIcyEnderCreeper;
	public static ItemFusion fusionItemIceGolem;
	public static ItemFusion fusionItemMagmaGolem;
	public static ItemFusion fusionItemPrisonSlime;
	public static ItemFusion fusionItemPrisonZombie;
	public static ItemFusion fusionItemPrisonSpider;
	public static ItemFusion fusionItemPrisonGolem;
	public static ItemFusion fusionItemGhasther;
	public static ItemFusion fusionItemAbomniableSnowman;
	public static ItemFusion fusionItemIllusioner;
	public static ItemFusion fusionItemWitherStorm;
	public static ItemTierItem batItem;
	public static ItemTierItem chickenItem;
	public static ItemTierItem cowItem;
	public static ItemTierItem mooshroomItem;
	public static ItemTierItem parrotItem;
	public static ItemTierItem pigItem;
	public static ItemTierItem rabbitItem;
	public static ItemTierItem sheepItem;
	public static ItemTierItem ozelotItem;
	public static ItemTierItem squidItem;
	public static ItemTierItem llamaItem;
	public static ItemTierItem villagerItem;
	public static ItemTierItem snowmanItem;
	public static ItemTierItem silverfishItem;
	public static ItemTierItem endermiteItem;
	public static ItemTierItem wolfItem;
	public static ItemTierItem spiderItem;
	public static ItemTierItem zombieItem;
	public static ItemTierItem skeletonItem;
	public static ItemTierItem creeperItem;
	public static ItemTierItem polarBearItem;
	public static ItemTierItem slimeItem;
	public static ItemTierItem magmacubeItem;
	public static ItemTierItem vexItem;
	public static ItemTierItem spiderjockeyItem;
	public static ItemTierItem chickenjockeyItem;
	public static ItemTierItem blazeItem;
	public static ItemTierItem endermanItem;
	public static ItemTierItem cavespiderItem;
	public static ItemTierItem pigzombieItem;
	public static ItemTierItem guardianItem;
	public static ItemTierItem ghastItem;
	public static ItemTierItem huskItem;
	public static ItemTierItem shulkerItem;
	public static ItemTierItem strayItem;
	public static ItemTierItem witchItem;
	public static ItemTierItem vindicatorItem;
	public static ItemTierItem witherskeletonItem;
	public static ItemTierItem killerrabbitItem;
	public static ItemTierItem elderguardianItem;
	public static ItemTierItem the4horsemenItem;
	public static ItemTierItem evokerItem;
	public static ItemTierItem giantItem;
	public static ItemTierItem villagergolemItem;
	public static ItemTierItem enderdragonItem;
	public static ItemTierItem witherItem;
	public static ItemTierItem eversourceItem;
	public static ItemTierItem iceSpiderItem;
	public static ItemTierItem creederItem;
	public static ItemTierItem icyEnderCreeperItem;
	public static ItemTierItem iceGolemItem;
	public static ItemTierItem magmaGolemItem;
	public static ItemTierItem prisonSlimeItem;
	public static ItemTierItem prisonZombieItem;
	public static ItemTierItem prisonSpiderItem;
	public static ItemTierItem prisonGolemItem;
	public static ItemTierItem ghastherItem;
	public static ItemTierItem abomniableSnowmanItem;
	public static ItemTierItem illusionerItem;
	public static ItemTierItem witherStormItem;
	public static Item darkstonecleaver;
	public static Item abyssalnitecleaver;
	public static Item refinedcoraliumcleaver;
	public static Item dreadiumcleaver;
	public static Item ethaxiumcleaver;
	public static Item peGunLevel1;
	public static Item peGunLevel2;
	public static Item peGunLevel3;
	public static Item peGunLevel4;
	public static Item peGunLevel5;
	public static Item abyssalPortalStaff;
	public static ItemFusion fusionItemAbyssalZombie;
	public static ItemFusion fusionItemAbyssalniteGolem;
	public static ItemFusion fusionItemChagarothSpawn;
	public static ItemFusion fusionItemChagarothFist;
	public static ItemFusion fusionItemCoraliumSquid;
	public static ItemFusion fusionItemDreadAbyssalniteGolem;
	public static ItemFusion fusionItemDreadling;
	public static ItemFusion fusionItemDreadSpawn;
	public static ItemFusion fusionItemDepthsGhoul;
	public static ItemFusion fusionItemShadowCreature;
	public static ItemFusion fusionItemGreaterDreadSpawn;
	public static ItemFusion fusionItemOmotholGhoul;
	public static ItemFusion fusionItemShadowMonster;
	public static ItemFusion fusionItemShoggoth;
	public static ItemFusion fusionItemRemnant;
	public static ItemFusion fusionItemSpectralDragon;
	public static ItemFusion fusionItemAsorah;
	public static ItemFusion fusionItemChagaroth;
	public static ItemFusion fusionItemDreadguard;
	public static ItemFusion fusionItemGatekeeperMinion;
	public static ItemFusion fusionItemLesserDreadbeast;
	public static ItemFusion fusionItemShadowBeast;
	public static ItemFusion fusionItemSkeletonGoliath;
	public static ItemFusion fusionItemSacthoth;
	public static ItemTierItem shadowCreatureItem;
	public static ItemTierItem shadowMonsterItem;
	public static ItemTierItem shadowBeastItem;
	public static ItemTierItem sacthothItem;
	public static ItemTierItem skeletonGoliathItem;
	public static ItemTierItem dreadguardItem;
	public static ItemTierItem depthsGhoulItem;
	public static ItemTierItem omotholGhoulItem;
	public static ItemTierItem chagarothSpawnItem;
	public static ItemTierItem chagarothFistItem;
	public static ItemTierItem dreadSpawnItem;
	public static ItemTierItem greaterDreadSpawnItem;
	public static ItemTierItem lesserDreadbeastItem;
	public static ItemTierItem chagarothItem;
	public static ItemTierItem abyssalniteGolemItem;
	public static ItemTierItem dreadAbyssalniteGolemItem;
	public static ItemTierItem remnantItem;
	public static ItemTierItem abyssalZombieItem;
	public static ItemTierItem dreadlingItem;
	public static ItemTierItem shoggothItem;
	public static ItemTierItem gatekeeperminionItem;
	public static ItemTierItem coraliumSquidItem;
	public static ItemTierItem spectralDragonItem;
	public static ItemTierItem asorahItem;
	public static ItemFusion fusionItemJzahar;
	public static ItemTierItem jzaharItem;
	
	public static Item draconicPortalStaff;
	public static ItemFusion fusionItemChaosGuardian;
	public static ItemTierItem chaosGuardianItem;
	
	public static ItemFusion fusionPigSpider;
	public static ItemFusion fusionMutantSnowGolem;
	public static ItemFusion fusionMutantZombie;
	public static ItemFusion fusionMutantCreeper;
	public static ItemFusion fusionMutantSkeleton;
	public static ItemFusion fusionMutantEnderman;
	public static ItemTierItem pigSpiderItem;
	public static ItemTierItem mutantSnowGolemItem;
	public static ItemTierItem mutantCreeperItem;
	public static ItemTierItem mutantSkeletonItem;
	public static ItemTierItem mutantZombieItem;
	public static ItemTierItem mutantEndermanItem;
	
	public static final List<ItemLearningBook> SKILL_BOOKS = new ArrayList<ItemLearningBook>();
	
	public static void ENMO()
	{
		init();
		register();
		BlockDispenser.DISPENSE_BEHAVIOR_REGISTRY.putObject(carrier, new BehaviorDefaultDispenseItem()
		{
			public ItemStack dispenseStack(IBlockSource source, ItemStack stack)
			{
				EnumFacing enumfacing = (EnumFacing)source.getBlockState().getValue(BlockDispenser.FACING);
				double d0 = source.getX() + (double)enumfacing.getFrontOffsetX();
				double d1 = (double)((float)(source.getBlockPos().getY() + enumfacing.getFrontOffsetY()) + 0.2F);
				double d2 = source.getZ() + (double)enumfacing.getFrontOffsetZ();
				
				@SuppressWarnings("unused")
				Entity entity = ItemCarrier.spawnMob(source.getWorld(), stack, d0, d1, d2);
				
				super.dispenseStack(source, stack);
				return stack;
			}
		});
		}

		public static void init()
		{
			manaContainer = new ItemManaCollector("mana_collector", 0);
			entropyContainer = new ItemManaCollector("entropy_collector", 1);
			artifact1 = new ItemManaCollector("infinite_well_spring", 2);
			witheredNetherStar = new ItemSimpleFoiled().setCreativeTab(ETab.engender).setUnlocalizedName("withered_nether_star").setRegistryName("withered_nether_star");
			woodencleaver = new ItemCleaver(ToolMaterial.WOOD, "wooden_cleaver", ETab.engender);
			stonecleaver = new ItemCleaver(ToolMaterial.STONE, "stone_cleaver", ETab.engender);
			ironcleaver = new ItemCleaver(ToolMaterial.IRON, "iron_cleaver", ETab.engender);
			goldencleaver = new ItemCleaver(ToolMaterial.GOLD, "golden_cleaver", ETab.engender);
			diamondcleaver = new ItemCleaver(ToolMaterial.DIAMOND, "diamond_cleaver", ETab.engender);
			statChecker = new ItemEngenderStatChecker();
			carrier = new ItemCarrier();
			heromaker = new ItemHeroMaker();
			lastchance = new ItemLastChance();
			trainingstick = new ItemTrainingStick();
			blowhorn = new ItemMoralHorn();
			blowhorn2 = new ItemDragonsHorn();
			convertingStaff = new ItemConvertingStaff();
			summoningStaff = new ItemSummoningStaff();
			commandingStaff = new ItemCommandingStaff();
			portalStaff = new ItemPortalStaff();
			learningBookBasic = new ItemLearningBook(0, "learningbook_basic", "Teach your mobs the basics of themselves.", 150, 10, 0.1f, 0.1f, 0.1f, 0.1f, 0.1f);
			learningBookBasicCombat = new ItemLearningBook(0, "learningbook_basic_combat", "Teach your mobs the basics of combat.", 100, 1, 0.5f, 0.0f, 0.1f, 0.1f, 0.0f);
			learningBookBasicCooking = new ItemLearningBook(0, "learningbook_basic_cooking", "Teach your mobs the basics of cooking.", 100, 1, 0.0f, 0.5f, 0.1f, 0.0f, 0.0f);
			learningBookBasicExercise = new ItemLearningBook(0, "learningbook_basic_exercise", "Teach your mobs the basics of exercise.", 100, 1, 0.0f, 0.0f, 0.1f, 0.1f, 0.5f);
			learningBookBasicKnowledge = new ItemLearningBook(0, "learningbook_basic_knowledge", "Teach your mobs simple knowledge.", 100, 15, 0.0f, 0.0f, 0.5f, 0.0f, 0.0f);
			
			learningBookModern = new ItemLearningBook(1, "learningbook_modern", "The history of all engendered mobs as we know it.", 75, 25, 0.2f, 0.2f, 0.2f, 0.2f, 0.2f);
			learningBookModernCombat = new ItemLearningBook(1, "learningbook_modern_combat", "How to properly wield your sword", 70, 10, 0.75f, 0.0f, 0.0f, 0.1f, 0.0f);
			learningBookModernBrute = new ItemLearningBook(1, "learningbook_modern_brute", "Learn about the history of Barbarians.", 50, 7, 1.25f, 0.1f, -0.1f, 0.0f, 0.0f);
			learningBookModernCooking = new ItemLearningBook(1, "learningbook_modern_cooking", "A guide to never burning your food again", 70, 10, 0.1f, 0.75f, 0.1f, 0.0f, 0.0f);
			learningBookModernEating = new ItemLearningBook(1, "learningbook_modern_eating", "Create good eating habbits", 50, 7, 0.0f, 0.75f, 0.1f, -0.1f, -0.1f);
			learningBookModernExercise = new ItemLearningBook(1, "learningbook_modern_exercise", "Go outside and exercise.", 70, 10, 0.0f, 0.1f, 0.0f, 0.3f, 0.75f);
			learningBookModernRunning = new ItemLearningBook(1, "learningbook_modern_running", "You can't win a battle if you can't escape from bad decisions.", 50, 7, -0.3f, 0.1f, 0.0f, 0.0f, 0.1f);
			learningBookModernKnowledge = new ItemLearningBook(1, "learningbook_modern_knowledge", "Learn how to calculate your opponent's next move.", 70, 50, 0.0f, 0.0f, 0.75f, 0.0f, 0.0f);
			learningBookModernPacifist = new ItemLearningBook(1, "learningbook_modern_pacifist", "Learn about the gigantic entity that rules the void.", 50, 20, -0.5f, 0.0f, 2.25f, -0.5f, -0.3f);
			
			learningBookAdvanced = new ItemLearningBook(2, "learningbook_advanced", "It's time to look into the future of Engender!", 50, 50, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f);
			learningBookAdvancedCombat = new ItemLearningBook(2, "learningbook_advanced_combat", "Knight armor and weaponry", 30, 30, 2.5f, 0.1f, 0.1f, 0.1f, -1.0f);
			learningBookAdvancedBrute = new ItemLearningBook(2, "learningbook_advanced_brute", "The history of Spartans", 20, 20, 8.0f, -0.75f, -1.0f, -5.0f, -5.0f);
			learningBookAdvancedWarrior = new ItemLearningBook(2, "learningbook_advanced_warrior", "The legend of an unknown warrior...", 15, 20, -4.0f, 0.0f, 1.0f, 1.5f, 0.0f);
			learningBookAdvancedCooking = new ItemLearningBook(2, "learningbook_advanced_cooking", "Now things are heating up!", 30, 30, -0.2f, 2.5f, 0.1f, 0.1f, -0.2f);
			learningBookAdvancedEating = new ItemLearningBook(2, "learningbook_advanced_eating", "Learn how to eat three times a day", 20, 20, 0.1f, 4.0f, 0.1f, -5.0f, -3.0f);
			learningBookAdvancedDieting = new ItemLearningBook(2, "learningbook_advanced_dieting", "When you get too fat, lose weight!", 15, 20, -7.5f, 7.5f, -0.75f, 0.5f, -0.25f);
			learningBookAdvancedExercise = new ItemLearningBook(2, "learningbook_advanced_exercise", "Time to get into motion!", 30, 30, 0.0f, 0.5f, -0.1f, 0.5f, 2.0f);
			learningBookAdvancedRunning = new ItemLearningBook(2, "learningbook_advanced_running", "Running faster is key to run faster!Wait wha?...", 20, 20, -0.5f, -0.5f, 0.0f, 0.0f, 4.0f);
			learningBookAdvancedLifting = new ItemLearningBook(2, "learningbook_advanced_lifting", "Time to use those arms for something!", 15, 20, 0.1f, -0.5f, -1.0f, 2.5f, 0.0f);
			learningBookAdvancedKnowledge = new ItemLearningBook(2, "learningbook_advanced_knowledge", "Learn how to form tactics.", 30, 100, -0.2f, 0.0f, 2.0f, -0.1f, -0.1f);
			learningBookAdvancedPacifist = new ItemLearningBook(2, "learningbook_advanced_pacifist", "Learn how to protest against an evil society.", 20, 30, -3.0f, 0.0f, 5.0f, -5.0f, -0.2f);
			learningBookAdvancedWisdom = new ItemLearningBook(2, "learningbook_advanced_wisdom", "\"Being wise takes a man to learn how to grow...\"", 15, 200, -0.2f, -0.5f, -2.0f, 0.0f, 0.0f);
			
			learningBookComplex = new ItemLearningBook(3, "learningbook_complex", "Staying together as one army.", 35, 100, 1.0f, 1.0f, 1.5f, 1.0f, 1.0f);
			learningBookComplexCombat = new ItemLearningBook(3, "learningbook_complex_combat", "How to keep yourself on guard", 15, 50, 8.5f, 0.5f, 1.0f, -0.5f, -4.0f);
			learningBookComplexBrute = new ItemLearningBook(3, "learningbook_complex_brute", "Heavy armor and weaponry", 10, 25, 15.5f, -10.0f, -10.0f, -1.0f, -1.0f);
			learningBookComplexWarrior = new ItemLearningBook(3, "learningbook_complex_warrior", "The historical ultimate blade...", 5, 25, -10.5f, 0.0f, 2.0f, 8.0f, 5.0f);
			learningBookComplexCooking = new ItemLearningBook(3, "learningbook_complex_cooking", "Chef Ramsay has joined the chapter.", 15, 50, 2.5f, 10.0f, 1.0f, -2.0f, -5.0f);
			learningBookComplexEating = new ItemLearningBook(3, "learningbook_complex_eating", "Eating healthy foods come a long way!", 10, 25, -15.0f, 15.0f, 0.2f, 2.0f, 1.0f);
			learningBookComplexDieting = new ItemLearningBook(3, "learningbook_complex_dieting", "Learn how to lose weight to feel better!", 5, 25, -10.0f, 20.5f, -1.0f, -2.0f, 1.0f);
			learningBookComplexExercise = new ItemLearningBook(3, "learningbook_complex_exercise", "Outpreforming your dog", 15, 50, -5.5f, 0.0f, -1.0f, 2.0f, 10.5f);
			learningBookComplexRunning = new ItemLearningBook(3, "learningbook_complex_running", "Running faster than the speed of the wind", 10, 25, -10.0f, 0.1f, -8.0f, -0.2f, 15.0f);
			learningBookComplexLifting = new ItemLearningBook(3, "learningbook_complex_lifting", "A guide to perfect hand-eye coordination", 5, 25, -5.5f, -5.5f, 0.5f, 15.5f, -0.5f);
			learningBookComplexKnowledge = new ItemLearningBook(3, "learningbook_complex_knowledge", "Learn about the world as a whole.", 15, 350, -2.0f, -2.0f, 20.0f, -2.0f, -2.0f);
			learningBookComplexPacifist = new ItemLearningBook(3, "learningbook_complex_pacifist", "How to run a peaceful society", 10, 175, -10.0f, 0.0f, 30.0f, -10.0f, 0.0f);
			learningBookComplexWisdom = new ItemLearningBook(3, "learningbook_complex_wisdom", "\"Never bring a sword to a ranged fight.\"", 5, 1000, -10.0f, -10.0f, 0.5f, -10.0f, 0.0f);
			
			learningBookMaster = new ItemLearningBook(4, "learningbook_master", "Now that everything is together, let's begin Engender!", 15, 250, 5.0f, 5.0f, 10.0f, 5.0f, 5.0f);
			learningBookMasterCombat = new ItemLearningBook(4, "learningbook_master_combat", "A master's guide to combat", 120, 1, 30.0f, -15.0f, 5.0f, -5.0f, -5.0f);
			learningBookMasterBrute = new ItemLearningBook(4, "learningbook_master_brute", "The legends of Gundyr", 7, 75, 50.0f, -30.0f, -5.0f, -5.0f, -5.0f);
			learningBookMasterWarrior = new ItemLearningBook(4, "learningbook_master_warrior", "Mastery of swordcraft", 5, 75, -20.0f, 10.0f, 5.0f, 10.0f, -5.0f);
			learningBookMasterCooking = new ItemLearningBook(4, "learningbook_master_cooking", "Never make anything raw again!", 10, 120, 0.0f, 30.0f, 1.0f, -5.0f, -5.0f);
			learningBookMasterEating = new ItemLearningBook(4, "learningbook_master_eating", "Making the perfect meal!", 7, 75, -10.0f, 45.0f, 2.0f, -10.0f, -5.0f);
			learningBookMasterDieting = new ItemLearningBook(4, "learningbook_master_dieting", "Best ways to lose unnecissary weight", 5, 75, -25.5f, 40.0f, -5.0f, 5.0f, 5.0f);
			learningBookMasterExercise = new ItemLearningBook(4, "learningbook_master_exercise", "Mastering Ultra-Instinct", 10, 120, -10.0f, -5.0f, 1f, 15.5f, 15.0f);
			learningBookMasterRunning = new ItemLearningBook(4, "learningbook_master_running", "Go faster than the speed of sound!", 7, 75, -5.0f, -10.0f, -2.0f, 1.0f, 30.0f);
			learningBookMasterLifting = new ItemLearningBook(4, "learningbook_master_lifting", "Win the match with faster blows!", 5, 75, -5.0f, 0.0f, 2.0f, 20.0f, -5.0f);
			learningBookMasterKnowledge = new ItemLearningBook(4, "learningbook_master_knowledge", "Know your opponent", 10, 3000, -5.0f, -5.0f, 35.0f, 0.0f, 0.0f);
			learningBookMasterPacifist = new ItemLearningBook(4, "learningbook_master_pacifist", "How to end world hunger", 7, 500, -15.5f, -5.0f, 45.0f, -15.5f, 0.5f);
			learningBookMasterWisdom = new ItemLearningBook(4, "learningbook_master_wisdom", "\"In war, everybody loses something...\"", 5, 25000, -10.0f, -5.0f, -30.1f, -5.0f, -1.0f);
			
			learningBookArtifactStrength = new ItemLearningBook(5, "learningbook_artifact_strength", "Learn how to wield a real weapon crafted by the gods.", 2, 100000, 100.0f, 0.0f, 0.0f, 0.0f, 0.0f);
			learningBookArtifactStamina = new ItemLearningBook(5, "learningbook_artifact_stamina", "There is a way to never feel exhausted.The power is yours.", 2, 100000, 0.0f, 100.0f, 0.0f, 0.0f, 0.0f);
			learningBookArtifactSpeed = new ItemLearningBook(5, "learningbook_artifact_speed", "Let's see if you can use your instincts...", 2, 100000, 0.0f, 0.0f, 0.0f, 100.0f, 100.0f);
			learningBookArtifactIntellegence = new ItemLearningBook(5, "learningbook_artifact_intelegence", "A god can never go without knowledge of the universe.", 2, 250000, 0.0f, 0.0f, 100.0f, 0.0f, 0.0f);
			
			learningBookArtifact = new ItemLearningBook(6, "learningbook_artifact", "Gain the knowledge of a god with a glance.", 1, 1000000, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f);
			
			batItem = new ItemBatItem(0);
			chickenItem = new ItemChickenItem(0);
			cowItem = new ItemCowItem(0);
			mooshroomItem = new ItemMooshroomItem(0);
			ozelotItem = new ItemOcelotItem(0);
			parrotItem = new ItemParrotItem(0);
			pigItem = new ItemPigItem(0);
			rabbitItem = new ItemRabbitItem(0);
			sheepItem = new ItemSheepItem(0);
			endermiteItem = new ItemEndermiteItem(1);
			llamaItem = new ItemLlamaItem(1);
			silverfishItem = new ItemSilverfishItem(1);
			snowmanItem = new ItemSnowmanItem(1);
			squidItem = new ItemSquidItem(1);
			villagerItem = new ItemVillagerItem(1);
			wolfItem = new ItemWolfItem(1);
			chickenjockeyItem = new ItemChickenJockeyItem(2);
			creeperItem = new ItemCreeperItem(2);
			magmacubeItem = new ItemMagmaCubeItem(2);
			polarBearItem = new ItemPolarBearItem(2);
			prisonSlimeItem = new ItemPrisonSlimeItem(2);
			skeletonItem = new ItemSkeletonItem(2);
			slimeItem = new ItemSlimeItem(2);
			spiderItem = new ItemSpiderItem(2);
			spiderjockeyItem = new ItemSpiderJockeyItem(2);
			vexItem = new ItemVexItem(2);
			zombieItem = new ItemZombieItem(2);
			blazeItem = new ItemBlazeItem(3);
			cavespiderItem = new ItemCaveSpiderItem(3);
			creederItem = new ItemCreederItem(3);
			endermanItem = new ItemEndermanItem(3);
			ghastItem = new ItemGhastItem(3);
			guardianItem = new ItemGuardianItem(3);
			huskItem = new ItemHuskItem(3);
			iceSpiderItem = new ItemIceSpiderItem(3);
			icyEnderCreeperItem = new ItemIcyEnderCreeperItem(3);
			killerrabbitItem = new ItemKillerBunnyItem(3);
			prisonSpiderItem = new ItemPrisonSpiderItem(3);
			prisonZombieItem = new ItemPrisonZombieItem(3);
			shulkerItem = new ItemShulkerItem(3);
			strayItem = new ItemStrayItem(3);
			vindicatorItem = new ItemVindicatorItem(3);
			witchItem = new ItemWitchItem(3);
			witherskeletonItem = new ItemWitherSkeletonItem(3);
			pigzombieItem = new ItemPigZombieItem(3);
			abomniableSnowmanItem = new ItemAbomniableSnowmanItem(4);
			elderguardianItem = new ItemElderGuardianItem(4);
			enderdragonItem = new ItemEnderDragonItem(4);
			eversourceItem = new ItemEversourceItem(4);
			evokerItem = new ItemEvokerItem(4);
			ghastherItem = new ItemGhastherItem(4);
			giantItem = new ItemGiantItem(4);
			iceGolemItem = new ItemIceGolemItem(4);
			illusionerItem = new ItemIllusionerItem(4);
			villagergolemItem = new ItemIronGolemItem(4);
			magmaGolemItem = new ItemMagmaGolemItem(4);
			prisonGolemItem = new ItemPrisonGolemItem(4);
			the4horsemenItem = new ItemSkeletonTrapItem(4);
			witherItem = new ItemWitherItem(4);
			witherStormItem = new ItemWitherStormItem(4);
			fusionItemBat = new ItemFusion(batItem, "fusionbat", 1, 0);
			fusionItemChicken = new ItemFusion(chickenItem, "fusionchicken", 1, 0);
			fusionItemCow = new ItemFusion(cowItem, "fusioncow", 2, 0);
			fusionItemMooshroom = new ItemFusion(mooshroomItem, "fusionmooshroom", 4, 0);
			fusionItemOzelot = new ItemFusion(ozelotItem, "fusionozelot", 2, 0);
			fusionItemParrot = new ItemFusion(parrotItem, "fusionparrot", 1, 0);
			fusionItemPig = new ItemFusion(pigItem, "fusionpig", 2, 0);
			fusionItemRabbit = new ItemFusion(rabbitItem, "fusionrabbit", 1, 0);
			fusionItemSheep = new ItemFusion(sheepItem, "fusionsheep", 3, 0);
			fusionItemEndermite = new ItemFusion(endermiteItem, "fusionendermite", 5, 0);
			fusionItemLlama = new ItemFusion(llamaItem, "fusionllama", 4, 0);
			fusionItemSilverfish = new ItemFusion(silverfishItem, "fusionsilverfish", 5, 0);
			fusionItemSnowman = new ItemFusion(snowmanItem, "fusionsnowman", 4, 0);
			fusionItemSquid = new ItemFusion(squidItem, "fusionsquid", 6, 0);
			fusionItemVillager = new ItemFusion(villagerItem, "fusionvillager", 15, 0);
			fusionItemWolf = new ItemFusion(wolfItem, "fusionwolf", 6, 0);
			fusionItemChickenJockey = new ItemFusion(chickenjockeyItem, "fusionchickenjockey", 25, 0);
			fusionItemCreeper = new ItemFusion(creeperItem, "fusioncreeper", 25, 0);
			fusionItemMagmaCube = new ItemFusion(magmacubeItem, "fusionmagmacube", 10, 0);
			fusionItemPolarBear = new ItemFusion(polarBearItem, "fusionpolarbear", 30, 0);
			fusionItemPrisonSlime = new ItemFusionMCSM(prisonSlimeItem, "fusionprisonslime", 12, 0);
			fusionItemSkeleton = new ItemFusion(skeletonItem, "fusionskeleton", 20, 0);
			fusionItemSlime = new ItemFusion(slimeItem, "fusionslime", 8, 0);
			fusionItemSpider = new ItemFusion(spiderItem, "fusionspider", 8, 0);
			fusionItemSpiderJockey = new ItemFusion(spiderjockeyItem, "fusionspiderjockey", 32, 0);
			fusionItemVex = new ItemFusion(vexItem, "fusionvex", 15, 0);
			fusionItemZombie = new ItemFusion(zombieItem, "fusionzombie", 20, 0);
			fusionItemBlaze = new ItemFusion(blazeItem, "fusionblaze", 75, 0);
			fusionItemCaveSpider = new ItemFusion(cavespiderItem, "fusioncavespider", 40, 0);
			fusionItemCreeder = new ItemFusionMCSM(creederItem, "fusioncreeder", 100, 0);
			fusionItemEnderman = new ItemFusion(endermanItem, "fusionenderman", 150, 0);
			fusionItemGhast = new ItemFusion(ghastItem, "fusionghast", 250, 0);
			fusionItemGuardian = new ItemFusion(guardianItem, "fusionguardian", 120, 0);
			fusionItemHusk = new ItemFusion(huskItem, "fusionhusk", 40, 0);
			fusionItemIceSpider = new ItemFusionMCSM(iceSpiderItem, "fusionicespider", 30, 0);
			fusionItemIcyEnderCreeper = new ItemFusionMCSM(icyEnderCreeperItem, "fusionicyendercreeper", 100, 0);
			fusionItemKillerRabbit = new ItemFusion(killerrabbitItem, "fusionkillerbunny", 200, 0);
			fusionItemPrisonSpider = new ItemFusionMCSM(prisonSpiderItem, "fusionprisonspider", 50, 0);
			fusionItemPrisonZombie = new ItemFusionMCSM(prisonZombieItem, "fusionprisonzombie", 60, 0);
			fusionItemShulker = new ItemFusion(shulkerItem, "fusionshulker", 200, 0);
			fusionItemStray = new ItemFusion(strayItem, "fusionstray", 80, 0);
			fusionItemVindicator = new ItemFusion(vindicatorItem, "fusionvindicator", 150, 0);
			fusionItemWitch = new ItemFusion(witchItem, "fusionwitch", 100, 0);
			fusionItemWitherSkeleton = new ItemFusion(witherskeletonItem, "fusionwitherskeleton", 125, 0);
			fusionItemPigZombie = new ItemFusion(pigzombieItem, "fusionpigzombie", 80, 0);
			fusionItemAbomniableSnowman = new ItemFusion(abomniableSnowmanItem, "fusionabomniablesnowman", 2500, 50);
			fusionItemElderGuardian = new ItemFusion(elderguardianItem, "fusionelderguardian", 1500, 20);
			fusionItemEnderDragon = new ItemFusion(enderdragonItem, "fusionenderdragon", 24000, 500);
			fusionItemEversource = new ItemFusionMCSM(eversourceItem, "fusioneversource", 5000, 1000);
			fusionItemEvoker = new ItemFusion(evokerItem, "fusionevoker", 6000, 350);
			fusionItemGhasther = new ItemFusion(ghastherItem, "fusionghasther", 4000, 150);
			fusionItemGiant = new ItemFusion(giantItem, "fusiongiant", 2000, 30);
			fusionItemMagmaGolem = new ItemFusionMCSM(magmaGolemItem, "fusionmagmagolem", 1000, 10);
			fusionItemIceGolem = new ItemFusionMCSM(iceGolemItem, "fusionicegolem", 800, 10);
			fusionItemIllusioner = new ItemFusion(illusionerItem, "fusionillusioner", 6000, 350);
			fusionItemVillagerGolem = new ItemFusion(villagergolemItem, "fusionirongolem", 1500, 20);
			fusionItemPrisonGolem = new ItemFusionMCSM(prisonGolemItem, "fusionprisongolem", 1600, 20);
			fusionItemSkeletonTrap = new ItemFusion(the4horsemenItem, "fusionskeletontrap", 2400, 80);
			fusionItemWither = new ItemFusion(witherItem, "fusionwither", 12000, 750);
			fusionItemWitherStorm = new ItemFusionMCSM(witherStormItem, "fusionwitherstorm", 100000, 5000);
		}
		
		public static void register()
		{
			GameData.register_impl(manaContainer);
			GameData.register_impl(entropyContainer);
			GameData.register_impl(artifact1);
			GameData.register_impl(witheredNetherStar);
			GameData.register_impl(woodencleaver);
			GameData.register_impl(stonecleaver);
			GameData.register_impl(ironcleaver);
			GameData.register_impl(goldencleaver);
			GameData.register_impl(diamondcleaver);
			GameData.register_impl(statChecker);
			GameData.register_impl(carrier);
			GameData.register_impl(heromaker);
			GameData.register_impl(lastchance);
			GameData.register_impl(trainingstick);
			GameData.register_impl(blowhorn);
			GameData.register_impl(blowhorn2);
			GameData.register_impl(convertingStaff);
			GameData.register_impl(summoningStaff);
			GameData.register_impl(commandingStaff);
			GameData.register_impl(portalStaff);
			
			GameData.register_impl(learningBookBasic);
			GameData.register_impl(learningBookBasicCombat);
			GameData.register_impl(learningBookBasicCooking);
			GameData.register_impl(learningBookBasicExercise);
			GameData.register_impl(learningBookBasicKnowledge);
			
			GameData.register_impl(learningBookModern);
			GameData.register_impl(learningBookModernCombat);
			GameData.register_impl(learningBookModernBrute);
			GameData.register_impl(learningBookModernCooking);
			GameData.register_impl(learningBookModernEating);
			GameData.register_impl(learningBookModernExercise);
			GameData.register_impl(learningBookModernRunning);
			GameData.register_impl(learningBookModernKnowledge);
			GameData.register_impl(learningBookModernPacifist);
			
			GameData.register_impl(learningBookAdvanced);
			GameData.register_impl(learningBookAdvancedCombat);
			GameData.register_impl(learningBookAdvancedBrute);
			GameData.register_impl(learningBookAdvancedWarrior);
			GameData.register_impl(learningBookAdvancedCooking);
			GameData.register_impl(learningBookAdvancedEating);
			GameData.register_impl(learningBookAdvancedDieting);
			GameData.register_impl(learningBookAdvancedExercise);
			GameData.register_impl(learningBookAdvancedRunning);
			GameData.register_impl(learningBookAdvancedLifting);
			GameData.register_impl(learningBookAdvancedKnowledge);
			GameData.register_impl(learningBookAdvancedPacifist);
			GameData.register_impl(learningBookAdvancedWisdom);
			
			GameData.register_impl(learningBookComplex);
			GameData.register_impl(learningBookComplexCombat);
			GameData.register_impl(learningBookComplexBrute);
			GameData.register_impl(learningBookComplexWarrior);
			GameData.register_impl(learningBookComplexCooking);
			GameData.register_impl(learningBookComplexEating);
			GameData.register_impl(learningBookComplexDieting);
			GameData.register_impl(learningBookComplexExercise);
			GameData.register_impl(learningBookComplexRunning);
			GameData.register_impl(learningBookComplexLifting);
			GameData.register_impl(learningBookComplexKnowledge);
			GameData.register_impl(learningBookComplexPacifist);
			GameData.register_impl(learningBookComplexWisdom);
			
			GameData.register_impl(learningBookMaster);
			GameData.register_impl(learningBookMasterCombat);
			GameData.register_impl(learningBookMasterBrute);
			GameData.register_impl(learningBookMasterWarrior);
			GameData.register_impl(learningBookMasterCooking);
			GameData.register_impl(learningBookMasterEating);
			GameData.register_impl(learningBookMasterDieting);
			GameData.register_impl(learningBookMasterExercise);
			GameData.register_impl(learningBookMasterRunning);
			GameData.register_impl(learningBookMasterLifting);
			GameData.register_impl(learningBookMasterKnowledge);
			GameData.register_impl(learningBookMasterPacifist);
			GameData.register_impl(learningBookMasterWisdom);
			
			GameData.register_impl(learningBookArtifactStrength);
			GameData.register_impl(learningBookArtifactStamina);
			GameData.register_impl(learningBookArtifactSpeed);
			GameData.register_impl(learningBookArtifactIntellegence);
			
			GameData.register_impl(learningBookArtifact);
			
			GameData.register_impl(fusionItemBat);
			GameData.register_impl(fusionItemChicken);
			GameData.register_impl(fusionItemCow);
			GameData.register_impl(fusionItemMooshroom);
			GameData.register_impl(fusionItemOzelot);
			GameData.register_impl(fusionItemParrot);
			GameData.register_impl(fusionItemPig);
			GameData.register_impl(fusionItemRabbit);
			GameData.register_impl(fusionItemSheep);
			GameData.register_impl(fusionItemEndermite);
			GameData.register_impl(fusionItemLlama);
			GameData.register_impl(fusionItemSilverfish);
			GameData.register_impl(fusionItemSnowman);
			GameData.register_impl(fusionItemSquid);
			GameData.register_impl(fusionItemVillager);
			GameData.register_impl(fusionItemWolf);
			GameData.register_impl(fusionItemChickenJockey);
			GameData.register_impl(fusionItemCreeper);
			GameData.register_impl(fusionItemMagmaCube);
			GameData.register_impl(fusionItemPolarBear);
			GameData.register_impl(fusionItemPrisonSlime);
			GameData.register_impl(fusionItemSkeleton);
			GameData.register_impl(fusionItemSlime);
			GameData.register_impl(fusionItemSpider);
			GameData.register_impl(fusionItemSpiderJockey);
			GameData.register_impl(fusionItemVex);
			GameData.register_impl(fusionItemZombie);
			GameData.register_impl(fusionItemBlaze);
			GameData.register_impl(fusionItemCaveSpider);
			GameData.register_impl(fusionItemCreeder);
			GameData.register_impl(fusionItemEnderman);
			GameData.register_impl(fusionItemGhast);
			GameData.register_impl(fusionItemGuardian);
			GameData.register_impl(fusionItemHusk);
			GameData.register_impl(fusionItemIceSpider);
			GameData.register_impl(fusionItemIcyEnderCreeper);
			GameData.register_impl(fusionItemKillerRabbit);
			GameData.register_impl(fusionItemPrisonSpider);
			GameData.register_impl(fusionItemPrisonZombie);
			GameData.register_impl(fusionItemShulker);
			GameData.register_impl(fusionItemStray);
			GameData.register_impl(fusionItemVindicator);
			GameData.register_impl(fusionItemWitch);
			GameData.register_impl(fusionItemWitherSkeleton);
			GameData.register_impl(fusionItemPigZombie);
			GameData.register_impl(fusionItemAbomniableSnowman);
			GameData.register_impl(fusionItemElderGuardian);
			GameData.register_impl(fusionItemEnderDragon);
			GameData.register_impl(fusionItemEversource);
			GameData.register_impl(fusionItemEvoker);
			GameData.register_impl(fusionItemGhasther);
			GameData.register_impl(fusionItemGiant);
			GameData.register_impl(fusionItemIceGolem);
			GameData.register_impl(fusionItemIllusioner);
			GameData.register_impl(fusionItemVillagerGolem);
			GameData.register_impl(fusionItemMagmaGolem);
			GameData.register_impl(fusionItemPrisonGolem);
			GameData.register_impl(fusionItemSkeletonTrap);
			GameData.register_impl(fusionItemWither);
			GameData.register_impl(fusionItemWitherStorm);
			GameData.register_impl(batItem);
			GameData.register_impl(chickenItem);
			GameData.register_impl(cowItem);
			GameData.register_impl(mooshroomItem);
			GameData.register_impl(ozelotItem);
			GameData.register_impl(parrotItem);
			GameData.register_impl(pigItem);
			GameData.register_impl(rabbitItem);
			GameData.register_impl(sheepItem);
			GameData.register_impl(endermiteItem);
			GameData.register_impl(llamaItem);
			GameData.register_impl(silverfishItem);
			GameData.register_impl(snowmanItem);
			GameData.register_impl(squidItem);
			GameData.register_impl(villagerItem);
			GameData.register_impl(wolfItem);
			GameData.register_impl(chickenjockeyItem);
			GameData.register_impl(creeperItem);
			GameData.register_impl(magmacubeItem);
			GameData.register_impl(polarBearItem);
			GameData.register_impl(prisonSlimeItem);
			GameData.register_impl(skeletonItem);
			GameData.register_impl(slimeItem);
			GameData.register_impl(spiderItem);
			GameData.register_impl(spiderjockeyItem);
			GameData.register_impl(vexItem);
			GameData.register_impl(zombieItem);
			GameData.register_impl(blazeItem);
			GameData.register_impl(cavespiderItem);
			GameData.register_impl(creederItem);
			GameData.register_impl(endermanItem);
			GameData.register_impl(ghastItem);
			GameData.register_impl(guardianItem);
			GameData.register_impl(huskItem);
			GameData.register_impl(iceSpiderItem);
			GameData.register_impl(icyEnderCreeperItem);
			GameData.register_impl(killerrabbitItem);
			GameData.register_impl(prisonSpiderItem);
			GameData.register_impl(prisonZombieItem);
			GameData.register_impl(shulkerItem);
			GameData.register_impl(strayItem);
			GameData.register_impl(vindicatorItem);
			GameData.register_impl(witchItem);
			GameData.register_impl(witherskeletonItem);
			GameData.register_impl(pigzombieItem);
			GameData.register_impl(abomniableSnowmanItem);
			GameData.register_impl(elderguardianItem);
			GameData.register_impl(enderdragonItem);
			GameData.register_impl(eversourceItem);
			GameData.register_impl(evokerItem);
			GameData.register_impl(ghastherItem);
			GameData.register_impl(giantItem);
			GameData.register_impl(iceGolemItem);
			GameData.register_impl(illusionerItem);
			GameData.register_impl(villagergolemItem);
			GameData.register_impl(magmaGolemItem);
			GameData.register_impl(prisonGolemItem);
			GameData.register_impl(the4horsemenItem);
			GameData.register_impl(witherItem);
			GameData.register_impl(witherStormItem);
		}
		
		public static void registerRenders()
		{
			ItemModelMesher renderItem = Minecraft.getMinecraft().getRenderItem().getItemModelMesher();
			
			registerItem(renderItem, manaContainer);
			registerItemSubbed(renderItem, manaContainer, 1);
			registerItemSubbed(renderItem, manaContainer, 2);
			registerItemSubbed(renderItem, manaContainer, 3);
			registerItemSubbed(renderItem, manaContainer, 4);
			registerItemSubbed(renderItem, manaContainer, 5);
			registerItemSubbed(renderItem, manaContainer, 6);
			registerItemSubbed(renderItem, manaContainer, 7);
			registerItemSubbed(renderItem, manaContainer, 8);
			registerItemSubbed(renderItem, manaContainer, 9);
			registerItem(renderItem, entropyContainer);
			registerItemSubbed(renderItem, entropyContainer, 1);
			registerItemSubbed(renderItem, entropyContainer, 2);
			registerItemSubbed(renderItem, entropyContainer, 3);
			registerItemSubbed(renderItem, entropyContainer, 4);
			registerItemSubbed(renderItem, entropyContainer, 5);
			registerItemSubbed(renderItem, entropyContainer, 6);
			registerItemSubbed(renderItem, entropyContainer, 7);
			registerItemSubbed(renderItem, entropyContainer, 8);
			registerItemSubbed(renderItem, entropyContainer, 9);
			registerItem(renderItem, artifact1);
			registerItem(renderItem, witheredNetherStar);
			registerItem(renderItem, woodencleaver);
			registerItem(renderItem, stonecleaver);
			registerItem(renderItem, ironcleaver);
			registerItem(renderItem, goldencleaver);
			registerItem(renderItem, diamondcleaver);
			registerItem(renderItem, statChecker);
			registerItem(renderItem, carrier);
			registerItem(renderItem, heromaker);
			registerItem(renderItem, lastchance);
			registerItem(renderItem, trainingstick);
			registerItem(renderItem, blowhorn);
			registerItem(renderItem, blowhorn2);
			registerItem(renderItem, convertingStaff);
			registerItemSubbed(renderItem, convertingStaff, 1);
			registerItemSubbed(renderItem, convertingStaff, 2);
			registerItemSubbed(renderItem, convertingStaff, 3);
			registerItemSubbed(renderItem, convertingStaff, 4);
			registerItem(renderItem, summoningStaff);
			registerItemSubbed(renderItem, summoningStaff, 1);
			registerItemSubbed(renderItem, summoningStaff, 2);
			registerItemSubbed(renderItem, summoningStaff, 3);
			registerItemSubbed(renderItem, summoningStaff, 4);
			registerItem(renderItem, commandingStaff);
			registerItemSubbed(renderItem, commandingStaff, 1);
			registerItemSubbed(renderItem, commandingStaff, 2);
			registerItemSubbed(renderItem, commandingStaff, 3);
			registerItemSubbed(renderItem, commandingStaff, 4);
			registerItem(renderItem, portalStaff);
			registerItemSubbed(renderItem, portalStaff, 1);
			registerItemSubbed(renderItem, portalStaff, 2);
			registerItemSubbed(renderItem, portalStaff, 3);
			registerItemSubbed(renderItem, portalStaff, 4);
			registerItem(renderItem, learningBookBasic);
			registerItem(renderItem, learningBookBasicCombat);
			registerItem(renderItem, learningBookBasicCooking);
			registerItem(renderItem, learningBookBasicExercise);
			registerItem(renderItem, learningBookBasicKnowledge);
			
			registerItem(renderItem, learningBookModern);
			registerItem(renderItem, learningBookModernCombat);
			registerItem(renderItem, learningBookModernBrute);
			registerItem(renderItem, learningBookModernCooking);
			registerItem(renderItem, learningBookModernEating);
			registerItem(renderItem, learningBookModernExercise);
			registerItem(renderItem, learningBookModernRunning);
			registerItem(renderItem, learningBookModernKnowledge);
			registerItem(renderItem, learningBookModernPacifist);
			
			registerItem(renderItem, learningBookAdvanced);
			registerItem(renderItem, learningBookAdvancedCombat);
			registerItem(renderItem, learningBookAdvancedBrute);
			registerItem(renderItem, learningBookAdvancedWarrior);
			registerItem(renderItem, learningBookAdvancedCooking);
			registerItem(renderItem, learningBookAdvancedEating);
			registerItem(renderItem, learningBookAdvancedDieting);
			registerItem(renderItem, learningBookAdvancedExercise);
			registerItem(renderItem, learningBookAdvancedRunning);
			registerItem(renderItem, learningBookAdvancedLifting);
			registerItem(renderItem, learningBookAdvancedKnowledge);
			registerItem(renderItem, learningBookAdvancedPacifist);
			registerItem(renderItem, learningBookAdvancedWisdom);
			
			registerItem(renderItem, learningBookComplex);
			registerItem(renderItem, learningBookComplexCombat);
			registerItem(renderItem, learningBookComplexBrute);
			registerItem(renderItem, learningBookComplexWarrior);
			registerItem(renderItem, learningBookComplexCooking);
			registerItem(renderItem, learningBookComplexEating);
			registerItem(renderItem, learningBookComplexDieting);
			registerItem(renderItem, learningBookComplexExercise);
			registerItem(renderItem, learningBookComplexRunning);
			registerItem(renderItem, learningBookComplexLifting);
			registerItem(renderItem, learningBookComplexKnowledge);
			registerItem(renderItem, learningBookComplexPacifist);
			registerItem(renderItem, learningBookComplexWisdom);
			
			registerItem(renderItem, learningBookMaster);
			registerItem(renderItem, learningBookMasterCombat);
			registerItem(renderItem, learningBookMasterBrute);
			registerItem(renderItem, learningBookMasterWarrior);
			registerItem(renderItem, learningBookMasterCooking);
			registerItem(renderItem, learningBookMasterEating);
			registerItem(renderItem, learningBookMasterDieting);
			registerItem(renderItem, learningBookMasterExercise);
			registerItem(renderItem, learningBookMasterRunning);
			registerItem(renderItem, learningBookMasterLifting);
			registerItem(renderItem, learningBookMasterKnowledge);
			registerItem(renderItem, learningBookMasterPacifist);
			registerItem(renderItem, learningBookMasterWisdom);
			
			registerItem(renderItem, learningBookArtifactStrength);
			registerItem(renderItem, learningBookArtifactStamina);
			registerItem(renderItem, learningBookArtifactSpeed);
			registerItem(renderItem, learningBookArtifactIntellegence);
			
			registerItem(renderItem, learningBookArtifact);
			
			registerItem(renderItem, fusionItemBat);
			registerItem(renderItem, fusionItemChicken);
			registerItem(renderItem, fusionItemCow);
			registerItem(renderItem, fusionItemMooshroom);
			registerItem(renderItem, fusionItemOzelot);
			registerItem(renderItem, fusionItemParrot);
			registerItem(renderItem, fusionItemPig);
			registerItem(renderItem, fusionItemRabbit);
			registerItem(renderItem, fusionItemSheep);
			registerItem(renderItem, fusionItemSquid);
			registerItem(renderItem, fusionItemEndermite);
			registerItem(renderItem, fusionItemLlama);
			registerItem(renderItem, fusionItemSilverfish);
			registerItem(renderItem, fusionItemSnowman);
			registerItem(renderItem, fusionItemVillager);
			registerItem(renderItem, fusionItemWolf);
			registerItem(renderItem, fusionItemCreeper);
			registerItem(renderItem, fusionItemMagmaCube);
			registerItem(renderItem, fusionItemPolarBear);
			registerItem(renderItem, fusionItemPrisonSlime);
			registerItem(renderItem, fusionItemSkeleton);
			registerItem(renderItem, fusionItemSlime);
			registerItem(renderItem, fusionItemSpider);
			registerItem(renderItem, fusionItemZombie);
			registerItem(renderItem, fusionItemVex);
			registerItem(renderItem, fusionItemSpiderJockey);
			registerItem(renderItem, fusionItemChickenJockey);
			registerItem(renderItem, fusionItemBlaze);
			registerItem(renderItem, fusionItemCaveSpider);
			registerItem(renderItem, fusionItemCreeder);
			registerItem(renderItem, fusionItemEnderman);
			registerItem(renderItem, fusionItemGhast);
			registerItem(renderItem, fusionItemGuardian);
			registerItem(renderItem, fusionItemHusk);
			registerItem(renderItem, fusionItemIceSpider);
			registerItem(renderItem, fusionItemIcyEnderCreeper);
			registerItem(renderItem, fusionItemKillerRabbit);
			registerItem(renderItem, fusionItemPrisonSpider);
			registerItem(renderItem, fusionItemPrisonZombie);
			registerItem(renderItem, fusionItemShulker);
			registerItem(renderItem, fusionItemStray);
			registerItem(renderItem, fusionItemVindicator);
			registerItem(renderItem, fusionItemWitch);
			registerItem(renderItem, fusionItemWitherSkeleton);
			registerItem(renderItem, fusionItemPigZombie);
			registerItem(renderItem, fusionItemAbomniableSnowman);
			registerItem(renderItem, fusionItemElderGuardian);
			registerItem(renderItem, fusionItemEnderDragon);
			registerItem(renderItem, fusionItemEversource);
			registerItem(renderItem, fusionItemEvoker);
			registerItem(renderItem, fusionItemGhasther);
			registerItem(renderItem, fusionItemGiant);
			registerItem(renderItem, fusionItemIceGolem);
			registerItem(renderItem, fusionItemIllusioner);
			registerItem(renderItem, fusionItemVillagerGolem);
			registerItem(renderItem, fusionItemMagmaGolem);
			registerItem(renderItem, fusionItemPrisonGolem);
			registerItem(renderItem, fusionItemSkeletonTrap);
			registerItem(renderItem, fusionItemWither);
			registerItem(renderItem, fusionItemWitherStorm);
			registerItem(renderItem, batItem);
			registerItem(renderItem, chickenItem);
			registerItem(renderItem, cowItem);
			registerItem(renderItem, mooshroomItem);
			registerItem(renderItem, ozelotItem);
			registerItem(renderItem, parrotItem);
			registerItem(renderItem, pigItem);
			registerItem(renderItem, rabbitItem);
			registerItem(renderItem, sheepItem);
			registerItem(renderItem, endermiteItem);
			registerItem(renderItem, llamaItem);
			registerItem(renderItem, silverfishItem);
			registerItem(renderItem, snowmanItem);
			registerItem(renderItem, squidItem);
			registerItem(renderItem, villagerItem);
			registerItem(renderItem, wolfItem);
			registerItem(renderItem, chickenjockeyItem);
			registerItem(renderItem, creeperItem);
			registerItem(renderItem, magmacubeItem);
			registerItem(renderItem, polarBearItem);
			registerItem(renderItem, prisonSlimeItem);
			registerItem(renderItem, skeletonItem);
			registerItem(renderItem, slimeItem);
			registerItem(renderItem, spiderItem);
			registerItem(renderItem, spiderjockeyItem);
			registerItem(renderItem, vexItem);
			registerItem(renderItem, zombieItem);
			registerItem(renderItem, batItem);
			registerItem(renderItem, blazeItem);
			registerItem(renderItem, cavespiderItem);
			registerItem(renderItem, creederItem);
			registerItem(renderItem, endermanItem);
			registerItem(renderItem, ghastItem);
			registerItem(renderItem, guardianItem);
			registerItem(renderItem, huskItem);
			registerItem(renderItem, iceSpiderItem);
			registerItem(renderItem, icyEnderCreeperItem);
			registerItem(renderItem, killerrabbitItem);
			registerItem(renderItem, prisonSpiderItem);
			registerItem(renderItem, prisonZombieItem);
			registerItem(renderItem, shulkerItem);
			registerItem(renderItem, strayItem);
			registerItem(renderItem, vindicatorItem);
			registerItem(renderItem, witchItem);
			registerItem(renderItem, witherskeletonItem);
			registerItem(renderItem, pigzombieItem);
			registerItem(renderItem, abomniableSnowmanItem);
			registerItem(renderItem, elderguardianItem);
			registerItem(renderItem, enderdragonItem);
			registerItem(renderItem, eversourceItem);
			registerItem(renderItem, evokerItem);
			registerItem(renderItem, ghastherItem);
			registerItem(renderItem, giantItem);
			registerItem(renderItem, iceGolemItem);
			registerItem(renderItem, illusionerItem);
			registerItem(renderItem, villagergolemItem);
			registerItem(renderItem, magmaGolemItem);
			registerItem(renderItem, prisonGolemItem);
			registerItem(renderItem, the4horsemenItem);
			registerItem(renderItem, witherItem);
			registerItem(renderItem, witherStormItem);
		}
		
		/**
		 * Create a Learning Book item [
		 * Tiers:
		 * 0 = Basic,* 1 = Modern,* 2 = Advanced,* 3 = Complex,* 4 = Master,* 5+ = Artifact ]
		 * @param LearningBook
		 * @param Name - Name of the book
		 * @param Description - Description of the book
		 * @param Durability - Max Available Successes
		 * @param Experience - Max Experience gained per read
		 * @param Strength - Max Experience gained per read
		 * @param Stamina - Max Experience gained per read
		 * @param Intellegence - Max Experience gained per read
		 * @param Dexterity - Max Experience gained per read
		 * @param Agility - Max Experience gained per read
		 */
		public static void createLearningBook(Item book, int tier, String name, String description, int durability, int experience, float strength, float stamina, float intelegence, float dexterity, float agility)
		{
			book = new ItemLearningBook(tier, name, description, durability, experience, strength, stamina, intelegence, dexterity, agility);
		}
		public static void registerItem(ItemModelMesher renderItem, Item item)
		{
			registerItemSubbed(renderItem, item, 0);
		}
		public static void registerItemSubbed(ItemModelMesher renderItem, Item item, int meta)
		{
			renderItem.register(item, meta, new ModelResourceLocation("ageofminecraft:" + item.getUnlocalizedName().substring(5), "inventory"));
		}
	}