package net.minecraft.AgeOfMinecraft.registry;

import net.minecraft.AgeOfMinecraft.EngenderMod;
import net.minecraft.util.ResourceLocation;
import net.minecraft.world.storage.loot.LootTableList;


public class ELoot extends LootTableList
{
	public static ResourceLocation ENTITIES_WITCH;
	public static ResourceLocation ENTITIES_BLAZE;
	public static ResourceLocation ENTITIES_CREEPER;
	public static ResourceLocation ENTITIES_SPIDER;
	public static ResourceLocation ENTITIES_CAVE_SPIDER;
	public static ResourceLocation ENTITIES_GIANT;
	public static ResourceLocation ENTITIES_SILVERFISH;
	public static ResourceLocation ENTITIES_ENDERMAN;
	public static ResourceLocation ENTITIES_GUARDIAN;
	public static ResourceLocation ENTITIES_ELDER_GUARDIAN;
	public static ResourceLocation ENTITIES_SHULKER_WHITE;
	public static ResourceLocation ENTITIES_SHULKER_ORANGE;
	public static ResourceLocation ENTITIES_SHULKER_MAGENTA;
	public static ResourceLocation ENTITIES_SHULKER_LIGHT_BLUE;
	public static ResourceLocation ENTITIES_SHULKER_YELLOW;
	public static ResourceLocation ENTITIES_SHULKER_LIME;
	public static ResourceLocation ENTITIES_SHULKER_PINK;
	public static ResourceLocation ENTITIES_SHULKER_GRAY;
	public static ResourceLocation ENTITIES_SHULKER_SILVER;
	public static ResourceLocation ENTITIES_SHULKER_CYAN;
	public static ResourceLocation ENTITIES_SHULKER_PURPLE;
	public static ResourceLocation ENTITIES_SHULKER_BLUE;
	public static ResourceLocation ENTITIES_SHULKER_BROWN;
	public static ResourceLocation ENTITIES_SHULKER_GREEN;
	public static ResourceLocation ENTITIES_SHULKER_RED;
	public static ResourceLocation ENTITIES_SHULKER_BLACK;
	public static ResourceLocation ENTITIES_IRON_GOLEM;
	public static ResourceLocation ENTITIES_SNOWMAN;
	public static ResourceLocation ENTITIES_RABBIT;
	public static ResourceLocation ENTITIES_CHICKEN;
	public static ResourceLocation ENTITIES_PIG;
	public static ResourceLocation ENTITIES_POLAR_BEAR;
	public static ResourceLocation ENTITIES_COW ;
	public static ResourceLocation ENTITIES_MUSHROOM_COW;
	public static ResourceLocation ENTITIES_WOLF;
	public static ResourceLocation ENTITIES_OCELOT;
	public static ResourceLocation ENTITIES_SHEEP;
	public static ResourceLocation ENTITIES_SHEEP_WHITE;
	public static ResourceLocation ENTITIES_SHEEP_ORANGE;
	public static ResourceLocation ENTITIES_SHEEP_MAGENTA;
	public static ResourceLocation ENTITIES_SHEEP_LIGHT_BLUE;
	public static ResourceLocation ENTITIES_SHEEP_YELLOW;
	public static ResourceLocation ENTITIES_SHEEP_LIME;
	public static ResourceLocation ENTITIES_SHEEP_PINK;
	public static ResourceLocation ENTITIES_SHEEP_GRAY;
	public static ResourceLocation ENTITIES_SHEEP_SILVER;
	public static ResourceLocation ENTITIES_SHEEP_CYAN;
	public static ResourceLocation ENTITIES_SHEEP_PURPLE;
	public static ResourceLocation ENTITIES_SHEEP_BLUE;
	public static ResourceLocation ENTITIES_SHEEP_BROWN;
	public static ResourceLocation ENTITIES_SHEEP_GREEN;
	public static ResourceLocation ENTITIES_SHEEP_RED;
	public static ResourceLocation ENTITIES_SHEEP_BLACK;
	public static ResourceLocation ENTITIES_BAT;
	public static ResourceLocation ENTITIES_SLIME;
	public static ResourceLocation ENTITIES_MAGMA_CUBE;
	public static ResourceLocation ENTITIES_GHAST;
	public static ResourceLocation ENTITIES_SQUID;
	public static ResourceLocation ENTITIES_ENDERMITE;
	public static ResourceLocation ENTITIES_ZOMBIE;
	public static ResourceLocation ENTITIES_ZOMBIE_PIGMAN;
	public static ResourceLocation ENTITIES_SKELETON;
	public static ResourceLocation ENTITIES_WITHER_SKELETON;
	public static ResourceLocation ENTITIES_STRAY;
	public static ResourceLocation ENTITIES_HUSK;
	public static ResourceLocation ENTITIES_ZOMBIE_VILLAGER;
	public static ResourceLocation ENTITIES_VILLAGER;
	public static ResourceLocation ENTITIES_EVOCATION_ILLAGER;
	public static ResourceLocation ENTITIES_VINDICATION_ILLAGER;
	public static ResourceLocation ENTITIES_LLAMA;
	public static ResourceLocation ENTITIES_VEX;
	public static ResourceLocation ENTITIES_ENDER_DRAGON;
	public static ResourceLocation ENTITIES_WITHER;
	public static ResourceLocation ENTITIES_COMMAND_BLOCK_WITHER;
	public static ResourceLocation ENTITIES_PORTAL;
	public static ResourceLocation ENTITIES_WITHER_STORM;
	public static ResourceLocation ENTITIES_WITHER_STORM_MULAGEN;
	public static ResourceLocation ENTITIES_WITHER_STORM_HEAD;
	public static ResourceLocation ENTITIES_WITHER_STORM_TENTACLE;
	public static ResourceLocation ENTITIES_WITHER_STORM_BIG_TENTACLE;
	public static ResourceLocation ENTITIES_CREEDER;
	public static ResourceLocation ENTITIES_ICE_SPIDER;
	public static ResourceLocation ENTITIES_ICY_ENDER_CREEPER;
	public static ResourceLocation ENTITIES_PRISON_SPIDER;
	public static ResourceLocation ENTITIES_PRISON_SLIME;
	public static ResourceLocation ENTITIES_PRISON_ZOMBIE;
	public static ResourceLocation ENTITIES_PRISON_GOLEM;
	public static ResourceLocation ENTITIES_ICE_GOLEM;
	public static ResourceLocation ENTITIES_MAGMA_GOLEM;
	public static ResourceLocation ENTITIES_GHASTHER;
	public static ResourceLocation ENTITIES_PARROT;
	public static ResourceLocation ENTITIES_ILLUSIONER;
	
	private static ResourceLocation register(String id)
	{
		return register(new ResourceLocation(EngenderMod.MODID, id));
	}

	public static void registerAllModdedLootTables()
	{
		ENTITIES_WITCH = register("entities/witch");
		ENTITIES_BLAZE = register("entities/blaze");
		ENTITIES_CREEPER = register("entities/creeper");
		ENTITIES_SPIDER = register("entities/spider");
		ENTITIES_CAVE_SPIDER = register("entities/cave_spider");
		ENTITIES_GIANT = register("entities/giant");
		ENTITIES_SILVERFISH = register("entities/silverfish");
		ENTITIES_ENDERMAN = register("entities/enderman");
		ENTITIES_GUARDIAN = register("entities/guardian");
		ENTITIES_ELDER_GUARDIAN = register("entities/elder_guardian");
		ENTITIES_SHULKER_WHITE = register("entities/shulker/white");
		ENTITIES_SHULKER_ORANGE = register("entities/shulker/orange");
		ENTITIES_SHULKER_MAGENTA = register("entities/shulker/magenta");
		ENTITIES_SHULKER_LIGHT_BLUE = register("entities/shulker/light_blue");
		ENTITIES_SHULKER_YELLOW = register("entities/shulker/yellow");
		ENTITIES_SHULKER_LIME = register("entities/shulker/lime");
		ENTITIES_SHULKER_PINK = register("entities/shulker/pink");
		ENTITIES_SHULKER_GRAY = register("entities/shulker/gray");
		ENTITIES_SHULKER_SILVER = register("entities/shulker/silver");
		ENTITIES_SHULKER_CYAN = register("entities/shulker/cyan");
		ENTITIES_SHULKER_PURPLE = register("entities/shulker/purple");
		ENTITIES_SHULKER_BLUE = register("entities/shulker/blue");
		ENTITIES_SHULKER_BROWN = register("entities/shulker/brown");
		ENTITIES_SHULKER_GREEN = register("entities/shulker/green");
		ENTITIES_SHULKER_RED = register("entities/shulker/red");
		ENTITIES_SHULKER_BLACK = register("entities/shulker/black");
		ENTITIES_IRON_GOLEM = register("entities/iron_golem");
		ENTITIES_SNOWMAN = register("entities/snowman");
		ENTITIES_RABBIT = register("entities/rabbit");
		ENTITIES_CHICKEN = register("entities/chicken");
		ENTITIES_PIG = register("entities/pig");
		ENTITIES_POLAR_BEAR = register("entities/polar_bear");
		ENTITIES_COW = register("entities/cow");
		ENTITIES_MUSHROOM_COW = register("entities/mushroom_cow");
		ENTITIES_WOLF = register("entities/wolf");
		ENTITIES_OCELOT = register("entities/ocelot");
		ENTITIES_SHEEP = register("entities/sheep");
		ENTITIES_SHEEP_WHITE = register("entities/sheep/white");
		ENTITIES_SHEEP_ORANGE = register("entities/sheep/orange");
		ENTITIES_SHEEP_MAGENTA = register("entities/sheep/magenta");
		ENTITIES_SHEEP_LIGHT_BLUE = register("entities/sheep/light_blue");
		ENTITIES_SHEEP_YELLOW = register("entities/sheep/yellow");
		ENTITIES_SHEEP_LIME = register("entities/sheep/lime");
		ENTITIES_SHEEP_PINK = register("entities/sheep/pink");
		ENTITIES_SHEEP_GRAY = register("entities/sheep/gray");
		ENTITIES_SHEEP_SILVER = register("entities/sheep/silver");
		ENTITIES_SHEEP_CYAN = register("entities/sheep/cyan");
		ENTITIES_SHEEP_PURPLE = register("entities/sheep/purple");
		ENTITIES_SHEEP_BLUE = register("entities/sheep/blue");
		ENTITIES_SHEEP_BROWN = register("entities/sheep/brown");
		ENTITIES_SHEEP_GREEN = register("entities/sheep/green");
		ENTITIES_SHEEP_RED = register("entities/sheep/red");
		ENTITIES_SHEEP_BLACK = register("entities/sheep/black");
		ENTITIES_BAT = register("entities/bat");
		ENTITIES_SLIME = register("entities/slime");
		ENTITIES_MAGMA_CUBE = register("entities/magma_cube");
		ENTITIES_GHAST = register("entities/ghast");
		ENTITIES_SQUID = register("entities/squid");
		ENTITIES_ENDERMITE = register("entities/endermite");
		ENTITIES_ZOMBIE = register("entities/zombie");
		ENTITIES_ZOMBIE_PIGMAN = register("entities/zombie_pigman");
		ENTITIES_SKELETON = register("entities/skeleton");
		ENTITIES_WITHER_SKELETON = register("entities/wither_skeleton");
		ENTITIES_STRAY = register("entities/stray");
		ENTITIES_HUSK = register("entities/husk");
		ENTITIES_PRISON_ZOMBIE = register("entities/prison_zombie");
		ENTITIES_PRISON_SLIME = register("entities/prison_slime");
		ENTITIES_PRISON_GOLEM = register("entities/prison_golem");
		ENTITIES_PRISON_SPIDER = register("entities/prison_spider");
		ENTITIES_CREEDER = register("entities/creeder");
		ENTITIES_ICE_SPIDER = register("entities/ice_spider");
		ENTITIES_ICE_GOLEM = register("entities/ice_golem");
		ENTITIES_ICY_ENDER_CREEPER = register("entities/icy_ender_creeper");
		ENTITIES_MAGMA_GOLEM = register("entities/magma_golem");
		ENTITIES_ZOMBIE_VILLAGER = register("entities/zombie_villager");
		ENTITIES_VILLAGER = register("entities/villager");
		ENTITIES_EVOCATION_ILLAGER = register("entities/evocation_illager");
		ENTITIES_VINDICATION_ILLAGER = register("entities/vindication_illager");
		ENTITIES_LLAMA = register("entities/llama");
		ENTITIES_VEX = register("entities/vex");
		ENTITIES_ENDER_DRAGON = register("entities/ender_dragon");
		ENTITIES_PORTAL = register("entities/portal");
		ENTITIES_WITHER = register("entities/wither");
		ENTITIES_GHASTHER = register("entities/ghasther");
		ENTITIES_COMMAND_BLOCK_WITHER = register("entities/command_block_wither");
		ENTITIES_WITHER_STORM = register("entities/wither_storm");
		ENTITIES_WITHER_STORM_MULAGEN = register("entities/wither_storm_mulagen");
		ENTITIES_WITHER_STORM_HEAD = register("entities/wither_storm_head");
		ENTITIES_WITHER_STORM_TENTACLE = register("entities/wither_storm_tentacle");
		ENTITIES_WITHER_STORM_BIG_TENTACLE = register("entities/wither_storm_big_tentacle");
		ENTITIES_ILLUSIONER = register("entities/illusioner");
		ENTITIES_PARROT = register("entities/parrot");
	}
}
